### ISSUE TITLE
IE9 RickRolls Everything

### ISSUE THREAD

**Issue by musocrat** [musocrat/jquery-video-lightning#10]
As funny as I would like it to be, based on my Browserling testing IE9 presents every element on the demo page as Rick Astley's Never Going to Give You Up. I wish this was done knowingly, but alas it wasn't.

I need to get my hands on earlier versions of IE to test and resolve. Will hopefully be able to do that soon.

**Comment by brandrick** [comment]
Also seeing this.

**Comment by musocrat** [comment]
I see why now, it's due to the lack of support for dataset. So it works when the `id` property is set on the initialization but not when it's set as a data attribute. I'm going to patch only this property, width, and height to work with data attributes (rather than having to individually grab all possible options from data attributes).

So, once patched setting the video-id in data attributes will work as will setting width and height, all other options will need to be added in initialization.


Will update shortly once patched.

**Comment by musocrat** [comment]
Okay, this is now patched in version [v3.0.5](https://github.com/musocrat/jquery-video-lightning/releases/tag/v3.0.5).
