### ISSUE TITLE
Background-color & border-color

### ISSUE THREAD

**Issue by Karlingue** [musocrat/jquery-video-lightning#11]
Hello

Can you add an option for modify background-color & border-color please ?

**Comment by musocrat** [comment]
Got you on the border's. I'll add that and update.

On background color are you referring to the color of the page overlay that the iframe sits on or the color of the actual iframe that the video will occupy?

**Comment by Karlingue** [comment]
Good :)

i say for actual iframe i think

**Comment by Karlingue** [comment]
The frame is black by defaut no ? (from local f-/login.html)

**Comment by musocrat** [comment]
Okay, this one is also live in 3.0.4. Let me know if that works.

**Comment by Karlingue** [comment]
Good :)
