### ISSUE TITLE
Add border-color on X

### ISSUE THREAD

**Issue by Karlingue** [musocrat/jquery-video-lightning#13]
Re :dancer: 

Can you Add border-color for x ? (background & text but not border :p)

Thanks

**Comment by musocrat** [comment]
Do you think the border should be on all 4 sides / full box or should the left border be left off to make it appear unified with the iframe?

**Comment by Karlingue** [comment]
Sorry, i don't understand all :( (frenchie :D)

can you show me a picture ? please

**Comment by musocrat** [comment]
Well, actually that was a premature question. Implementing it the way I suggested is going to add more complexity than the plugin is designed for. It could still be achieved with external CSS using the class names (.video, .video-close, .video-iframe).

Regardless I'm implementing a basic border (actually using the css property `outline` rather than `border` as it presents better with the iframe).

**Comment by Karlingue** [comment]
Ok

Idea : maybe possible the X on TOP-LEFT or TOP-RIGHT or BOTTOM-LEFT or BOTTOM-RIGHT

xPosition: top-left;
xPosition: top-right;
xPosition: bottom-left;
xPosition: bottom-right;

I think it's fun :)

**Comment by musocrat** [comment]
Okay, this one is live in 3.0.4. Let me know if that works.

**Comment by Karlingue** [comment]
Humm, i have a bug, why outline and not border ?

Border : http://s2.postimg.org/m26ea98ol/image.jpg
Outline : http://s9.postimg.org/esjib5zt7/Sans_titre_4.jpg

**Comment by musocrat** [comment]
Ah, yeah. I hadn't considered the effect of only the X having a border (outline). I used outline because on the iframe border pushes into the X a bit too much. I'll play with a few other params and see if I can find a good border solution.

**Comment by Karlingue** [comment]
Check https://developer.mozilla.org/en/docs/Web/CSS/box-sizing :)

**Comment by musocrat** [comment]
That was indeed the answer. Thanks for steering me in the right direction ;)

Just pushed that change. Let me know if that doesn't do it

**Comment by musocrat** [comment]
Closing this one, but let me know if it it needs any more tweaking. Thanks.
