### ISSUE TITLE
Add responsive

### ISSUE THREAD

**Issue by Machou** [musocrat/jquery-video-lightning#16]
Hello

Can you add responsive compatibility please ? :)

**Comment by musocrat** [comment]
I do need to get that added back. It was once there but got overlooked in the v3 update. I'll let you know once I've made some progress on this one.

**Comment by Machou** [comment]
Ok thanks

Do you have a date to release it ?

**Comment by musocrat** [comment]
I don't yet. As soon as I do I'll update

**Comment by Machou** [comment]
So ? :dancer:

**Comment by musocrat** [comment]
Sorry for the delay. I've got this added back in 3.0.7. It responds to starting screen width, but not resizing. Adding resizing responsiveness comes at a significant cost to performance, so I chose to omit that here.
