### ISSUE TITLE
Manually trigger the interface

### ISSUE THREAD

**Issue by khanhhaduc** [musocrat/jquery-video-lightning#17]
Hi there,

Is there anyway I can manually trigger the video to show?
I've tried using Jquery to trigger the click events on the elements but it doesn't seem to work. It does work when I actually click on it though

Thanks a lot

**Comment by khanhhaduc** [comment]
I found out why it wasn't working. The event it was listening to was 'mouseup'. changed it to 'click' and it's all good for me now

**Comment by musocrat** [comment]
Awesome, glad you got it worked out. Another method would be to identify the instance (stored in an array under the vlData global) and call the play() and stop() methods.

As an example:
vlData.instances.filter((inst) => !!inst.el.matches('.video-link3'))[0].play()

Note, this particular example would not be highly browser compatible but you could certainly do it in a more compatible way.

**Comment by thebrain1973** [comment]
Hi, The change works like a charm, i can start video automatically entering the page.
There is a problem, when the video is started automatically the autoclose parameter is ignored and the video is not closed at the end.
By the way, If i click on the link to start the video on the page, the autoclose parameter work as expected.

Any idea on how to solve this problem?
Thanks.

Alessandro.
