### ISSUE TITLE
Some youtube wont play on lightbox

### ISSUE THREAD

**Issue by gitmadz** [musocrat/jquery-video-lightning#19]
Hi Musocrat Team some of our youtube wont play on the lightbox here's the below ID's wont play the video

TU6B-5mmP_0
YT-CjRkkYWE
mWWh-NEywrg

ive noticed these ID's have dashed might be the code wont work if the id's have dashed on it

**Comment by musocrat** [comment]
Can you check the version number in the js file and let me know which it is. That should have been resolved in a previous release, but if not I'll get it fixed

**Comment by gitmadz** [comment]
here's the version of the js file
/*! jQuery v1.11.1

**Comment by musocrat** [comment]
Actually it should be in `videoLightning.min.js`, `videoLightning.min.js`, `videoLightning.min.js`, `jquery-video-lightning.min.js`, or `jquery-video-lightning.js`

**Comment by gitmadz** [comment]
Here's the 3 files included to my site
https://surething.com.au/assets/pop/jquery-video-lightning.js
https://surething.com.au/assets/pop/jquery-latest.min.js
https://surething.com.au/assets/pop/jquery-video-lightning.css

and on link below you can see the other videos are working and 2 of them on this page are not
https://surething.com.au/schoolies/videos/

**Comment by musocrat** [comment]
Try upgrading to the latest release.

Add https://raw.githubusercontent.com/musocrat/jquery-video-lightning/master/dist/videoLightning.min.js to the `/assets/pop/` directory and change the reference from `<script src="/assets/pop/jquery-video-lightning.js"></script>` to `<script src="/assets/pop/videoLightning.min.js"></script>`

That should fix it. Let me know if it doesn't.
