### ISSUE TITLE
Popover Feature Question

### ISSUE THREAD

**Issue by FrankoGitHub** [musocrat/jquery-video-lightning#7]
Hello, a short question:
Is it possible to change the Popover behavior from click event to hover?
So that the video preview starts by hovering over an element.

Thanks
( sorry for the english )

**Comment by musocrat** [comment]
Sorry for the delay on this one. I've re-written VL to be standalone (jQuery not required) and use the iframe js API. I'm currently implementing popovers with the peek / hover option. This will be a proper implementation

I'm hoping to have it released within the coming week. I'll update when it's live.

**Comment by musocrat** [comment]
Alright, 3.0 is out and this one is ready to go. Thanks for the awesome suggestion.
