### ISSUE TITLE
Close after video end

### ISSUE THREAD

**Issue by fedegonzaleznavarro** [musocrat/jquery-video-lightning#8]
Any progress with that feature?
I wish I contribute but my skills are non-existent :/
Everything else works great!

**Comment by musocrat** [comment]
I wish I could say yes, but I have not. It will require changing from using the ugly iframe / uri based initialization jqvl uses now to the js initialization we should be using anyway.

I'm not sure how soon I'll be able to get around to making that change. There are a couple of other loose ends I need to tie up as well in transitioning to using a proper js init of the players.

We'll leave this open and as soon as I am able to put some time toward it I'll update.

**Comment by fedegonzaleznavarro** [comment]
Awesome, thanks for your answer and time!

**Comment by musocrat** [comment]
Sorry for the delay on this one. I've re-written VL to be standalone (jQuery not required) and use the iframe js API. Autoclose is functioning in this upcoming release. I'm currently implementing Vimeo and popovers then I'll release it with updated docs.

I'll let you know when it's ready.

**Comment by musocrat** [comment]
Alright, 3.0 is out and this one is ready to go.

**Comment by pondahardik** [comment]
I am working on YouTube videos. And auto-close is not working somehow. I downloaded code and in the DEMO it works fine but as soon as I put the script to mine, lightbox pops up, video plays but doesn't close after it ends. any suggestion?
